title: Code Of Toth
theme: null
name: jhonny111s
description: web developer
avatar: https://avatars3.githubusercontent.com/u/4080701?s=400&u=edf30c1e0ed5a1e458fbc895bfcb1b760d23e78b&v=4
encoding: UTF-8
sass:
  sass_dir: _sass
